# Generated by Django 4.0.4 on 2022-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='duration',
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.TextField(),
        ),
    ]
